# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proto

class AttrType(object):
    INT = 0
    FLOAT = 1
    STRING = 2
    INTS = 3
    FLOATS = 4
    STRINGS = 5
    BOOLEAN = 6
    BOOLEANS = 7
    BLOCK = 8
    LONG = 9
    BLOCKS = 10
    LONGS = 11
    FLOAT64S = 12
    VAR = 13
    VARS = 14
    FLOAT64 = 15

