# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CombinedParamsDesc(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsCombinedParamsDesc(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CombinedParamsDesc()
        x.Init(buf, n + offset)
        return x

    # CombinedParamsDesc
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CombinedParamsDesc
    def Params(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from paddle.lite.fbs.proto.ParamDesc import ParamDesc
            obj = ParamDesc()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CombinedParamsDesc
    def ParamsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CombinedParamsDesc
    def ParamsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def CombinedParamsDescStart(builder): builder.StartObject(1)
def CombinedParamsDescAddParams(builder, params): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(params), 0)
def CombinedParamsDescStartParamsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def CombinedParamsDescEnd(builder): return builder.EndObject()
