# automatically generated by the FlatBuffers compiler, do not modify

# namespace: proto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OpVersionMap(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOpVersionMap(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OpVersionMap()
        x.Init(buf, n + offset)
        return x

    # OpVersionMap
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OpVersionMap
    def Pair(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from paddle.lite.fbs.proto.OpVersionMap_.OpVersionPair import OpVersionPair
            obj = OpVersionPair()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # OpVersionMap
    def PairLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # OpVersionMap
    def PairIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def OpVersionMapStart(builder): builder.StartObject(1)
def OpVersionMapAddPair(builder, pair): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(pair), 0)
def OpVersionMapStartPairVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def OpVersionMapEnd(builder): return builder.EndObject()
