# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VarType_

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReaderDesc(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsReaderDesc(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReaderDesc()
        x.Init(buf, n + offset)
        return x

    # ReaderDesc
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReaderDesc
    def DenseTensor(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from paddle.lite.fbs.proto.VarType_.DenseTensorDesc import DenseTensorDesc
            obj = DenseTensorDesc()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ReaderDesc
    def DenseTensorLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ReaderDesc
    def DenseTensorIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ReaderDescStart(builder): builder.StartObject(1)
def ReaderDescAddDenseTensor(builder, denseTensor): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(denseTensor), 0)
def ReaderDescStartDenseTensorVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def ReaderDescEnd(builder): return builder.EndObject()
