# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VarType_

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Tuple(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTuple(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Tuple()
        x.Init(buf, n + offset)
        return x

    # Tuple
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Tuple
    def ElementType(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Tuple
    def ElementTypeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Tuple
    def ElementTypeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Tuple
    def ElementTypeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def TupleStart(builder): builder.StartObject(1)
def TupleAddElementType(builder, elementType): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(elementType), 0)
def TupleStartElementTypeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TupleEnd(builder): return builder.EndObject()
