# automatically generated by the FlatBuffers compiler, do not modify

# namespace: VarType_

class Type(object):
    BOOL = 0
    INT16 = 1
    INT32 = 2
    INT64 = 3
    FP16 = 4
    FP32 = 5
    FP64 = 6
    DENSE_TENSOR = 7
    SELECTED_ROWS = 8
    FEED_MINIBATCH = 9
    FETCH_LIST = 10
    STEP_SCOPES = 11
    LOD_RANK_TABLE = 12
    DENSE_TENSOR_ARRAY = 13
    PLACE_LIST = 14
    READER = 15
    RAW = 17
    TUPLE = 18
    SIZE_T = 19
    UINT8 = 20
    INT8 = 21

