# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OpVersionMap_

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class OpVersionPair(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsOpVersionPair(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = OpVersionPair()
        x.Init(buf, n + offset)
        return x

    # OpVersionPair
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # OpVersionPair
    def OpName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # OpVersionPair
    def OpVersion(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from paddle.lite.fbs.proto.OpVersion import OpVersion
            obj = OpVersion()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def OpVersionPairStart(builder): builder.StartObject(2)
def OpVersionPairAddOpName(builder, opName): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(opName), 0)
def OpVersionPairAddOpVersion(builder, opVersion): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(opVersion), 0)
def OpVersionPairEnd(builder): return builder.EndObject()
