# automatically generated by the FlatBuffers compiler, do not modify

# namespace: CompatibleInfo_

class Type(object):
    COMPATIBLE = 0
    DEFINITELY_NOT = 1
    POSSIBLE = 2
    BUG_FIX = 3
    PRECISION_CHANGE = 4

