# automatically generated by the FlatBuffers compiler, do not modify

# namespace: OpDesc_

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Var(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsVar(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Var()
        x.Init(buf, n + offset)
        return x

    # Var
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Var
    def Parameter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Var
    def Arguments(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # Var
    def ArgumentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Var
    def ArgumentsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def VarStart(builder): builder.StartObject(2)
def VarAddParameter(builder, parameter): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(parameter), 0)
def VarAddArguments(builder, arguments): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(arguments), 0)
def VarStartArgumentsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def VarEnd(builder): return builder.EndObject()
