# Copyright 2023-2024 Arm Limited and/or its affiliates.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# pyre-unsafe

from . import ( #noqa
     op_arg_max,
     op_calib_test,
     op_add_test,
     op_conv2d_test,
     op_depthwise_conv2d_test,
     op_avg_pool2d_test,
     op_fc_test,
     op_sigmoid_test,
     op_mul_test,
     op_concat_tosa,
     op_fusion_elementwise_add_activation_tosa,
     op_relu_tosa,
     op_reshape_tosa,
     op_split_tosa,
     op_shuffle_channel_tosa,
     #op_upsample_nearest2d_tosa,
     op_dropout_test,
     op_hardsigmoid_test,
     op_hardswish_test,
     op_upsample_bilinear_test,
     op_upsample_nearest2d_test,
     tosa_op_scale,
     op_add_activate_test,
     op_full_test,
     op_max_pool2d_test

)

# from . import (  # noqa
#     node_visitor,
#     op_add,
#     op_avg_pool2d,
#     op_batch_norm,
#     op_bmm,
#     op_cat,
#     op_conv2d,
#     op_dequant,
#     op_exp,
#     op_full,
#     op_get_item,
#     op_hardtanh,
#     op_log,
#     op_max,
#     op_max_pool2d,
#     op_min,
#     op_mm,
#     op_mul,
#     op_permute,
#     op_quant,
#     op_reciprocal,
#     op_relu,
#     op_repeat,
#     op_rshift,
#     op_rsqrt,
#     op_select,
#     op_sigmoid,
#     op_slice,
#     op_squeeze,
#     op_sub,
#     op_sum,
#     op_tanh,
#     op_to_copy,
#     op_transpose,
#     op_unsqueeze,
#     op_upsample_nearest2d,
#     op_view,
# )
